### ISSUE TITLE
DNS Record creation fails

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#106]
Hello! As shown in the following screenshot, DNS record creation fails with Powerview, but I've confirmed to have it working with other tools such as bloodyAD or dnstool.py.

![immagine](https://github.com/user-attachments/assets/0e3fc44c-b3e2-4633-9397-e90c00d3b994)

Activating the debug output the following is shown:
![immagine](https://github.com/user-attachments/assets/cf94ab40-73bf-4df5-bb35-58b9033dd7b1)

Please keep up the good work, this is an amazing tool!
Thanks!

**Comment by H0j3n** [comment]
We assumed the error you encountered is because of Kerberos auth. The issue we suspect might be coming from the usage of False (boolean) in the 'dNSTombstoned'. 

Ref: https://stackoverflow.com/questions/26770259/how-do-i-modify-a-boolean-ldap-active-directory-attribute-using-netldap

We have fixed the issue by hardcoding "FALSE" (string) in the 'dNSTombstoned'. Please test in the dev branch and let us know if it works. Much appreciated!

**Comment by GeisericII** [comment]
Hello! I can confirm the fix works properly, thanks for your quick response, closing the issue!
