### ISSUE TITLE
DNS WildCard record

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#107]
Hello again!

While playing with DNS records I realized that PowerView doesn't allow creating WildCard DNS records. Actually it technically does, but the code that handles the function performs a sanity check whether the `*` record exists.
But, by doing so, it returns the first record in the DNS zone and "detects" that the record already exists.

To confirm that PowerView can actually add a WildCard DNS record I removed the lines of code that perform the search, and I can confirm that the WildCard has been successfully added.
![immagine](https://github.com/user-attachments/assets/83a513ce-9ba7-4eec-b536-f0ccf10a8c32)

![immagine](https://github.com/user-attachments/assets/a8a15b0c-b406-43d7-a7ad-997aa3a51837)

I would suggest the following approach to handle Wildcards:
Create a set of function `Add/Disable-DNSWildCard` that only takes the RecordAddress as argument and creates/disables the record.

Removing the DNS record would have no effect on the actual name resolution as the wildcard will remain in the DC memory unless the DNS service is restarted or the zone manually reloaded. Therefore the "disable" operation would be required to change the value of the DNS record to something like 0.0.0.0. 

Finally, speaking of changing DNS record values, the function handling records updates would need slight modification to 
allow an operator to edit the WildCard record (becoming therefore a superset of the Disable function).

If there is anything I can help you with, please do let me know, thanks!

**Comment by aniqfakhrul** [comment]
Thats actually true. Thanks for pointing that out. We might need to implement this in other modules as well allowing wildcard (*) object to be added.

**Comment by aniqfakhrul** [comment]
First off, I have removed the lines in `Add-DomainDNSRecord` where it checks if the dns exists because ldap will throw error if it exists anyway. Added character escape to avoid confusion with ldap filter wildcard (\*) and dns wildcard (\*). So adding and removing wildcard dns is not an issue now (as far as ive checked).
![image](https://github.com/user-attachments/assets/bc3e86d4-4a58-4294-8b0a-2f355cf52258)

Referring to "disabling" wildcard dns, thats new to me. Thanks for that! I've also added new module as per your suggestion, `Disable-DomainDNSRecord` to point whatever record to "0.0.0.0".

![image](https://github.com/user-attachments/assets/88a7a567-8833-4501-87b1-fd2e220bb3ec)

Please verify if this works.

**Comment by GeisericII** [comment]
Everything works as expected, wonderfully done! Closing the issue, thanks for the quick responses and code changes!
